from __future__ import annotations

"""One-generation/one-update production PPO runner for Order 9.

Collection is intentionally a separate real-Isaac operation.  This runner
accepts one immutable stochastic rollout manifest generated by the immediate
parent checkpoint, performs exactly one PPO update, and emits a new strict
checkpoint.  Reusing any rollout generation in the checkpoint lineage fails
closed.
"""

import json
import math
import os
import random
import tempfile
import time
from dataclasses import dataclass, field, replace
from pathlib import Path
from typing import Any, Callable, Mapping, Sequence

import torch
from torch import nn

from amsrr.policies.order9_design_policy import Order9AutoregressiveDesignPolicy
from amsrr.policies.order9_high_level_policy import Order9AutoregressiveHighLevelPolicy
from amsrr.policies.order9_low_level_policy import (
    Order9ContactResidualPhaseConditionedActorCritic,
    Order9ContactSpacePhaseConditionedActorCritic,
    Order9MorphologyInvariantCompressionActorCritic,
    Order9PhaseConditionedActorCritic,
)
from amsrr.schemas.common import SchemaBase, SchemaValidationError, require_non_empty
from amsrr.schemas.datasets import (
    DatasetSplit,
    InteractionTrajectoryRecord,
    LowLevelControlRecord,
    SequentialDesignTrajectoryRecord,
)
from amsrr.schemas.order9 import Order9PolicyFamily
from amsrr.schemas.physical_model import PhysicalModel
from amsrr.training.order9_checkpoints import (
    load_order9_policy_checkpoint,
    save_order9_policy_checkpoint,
)
from amsrr.training.order9_curriculum import (
    Order9CurriculumStage,
    Order9LearningConfig,
    Order9LearningMode,
    Order9LearningTarget,
    Order9PPOOptimizationConfig,
    order9_ppo_optimization,
    require_order9_stage_execution_allowed,
)
from amsrr.training.order9_curriculum_lineage import (
    load_order9_stage_parent_checkpoint,
)
from amsrr.training.order9_factorized_actor_credit import (
    ORDER9_FACTORIZED_ACTOR_CREDIT_CHANNELS,
    ORDER9_FACTORIZED_ACTOR_CREDIT_VERSION,
)
from amsrr.training.order9_c3_action_contract import (
    ORDER9_C3_ACTION_CONTRACTS,
    order9_c3_action_contract_global_dimension,
    order9_c3_action_contract_uses_full_policy,
)
from amsrr.training.order9_runtime_load import Order9RuntimeLoadMonitor
from amsrr.training.order9_dataset import (
    Order9DatasetBundle,
    load_order9_dataset,
    validate_order9_dataset_for_stage,
)
from amsrr.training.order9_offline_training import (
    build_order9_checkpoint_metadata,
    order9_checkpoint_input_hashes,
)
from amsrr.training.order9_pipeline import order9_schedule_hash, order9_stage_by_id
from amsrr.training.order9_ppo import (
    Order9PPOUpdateResult,
    update_order9_pi_d_ppo,
    update_order9_pi_h_ppo,
    update_order9_pi_l_ppo,
)
from amsrr.training.order9_tensor_on_policy_dataset import (
    Order9TensorPiLDatasetBundle,
    validate_order9_tensor_pi_l_dataset_for_stage,
)
from amsrr.training.order9_tensor_pi_l_ppo import (
    ORDER9_CONTACT_HEAD_EXTRA_OPTIMIZER_CONTRACT,
    update_order9_tensor_pi_l_ppo,
)
from amsrr.utils.hashing import hash_file


ORDER9_ONLINE_TRAINING_VERSION = "order9_one_generation_one_ppo_update_v2_preloaded"


def _order9_c3_action_contract_trainable_prefixes(
    model: Order9ContactResidualPhaseConditionedActorCritic,
    *,
    global_dimension: int,
) -> tuple[str, ...]:
    """Return the actor/critic parameters owned by an explicit C3 contract.

    The v5 compatibility actor encodes coordinated compression in a selected
    joint coordinate.  The approved v6 actor instead owns a dedicated
    morphology-invariant scalar head; training the inherited v5 decoder would
    silently restore topology-dependent action semantics.
    """

    compression_prefixes = (
        (
            "contact_compression_actor_mean.",
            "contact_compression_actor_log_std",
            "contact_compression_module_count_bias",
        )
        if isinstance(model, Order9MorphologyInvariantCompressionActorCritic)
        else ("contact_residual_decoder.",)
    )
    global_prefixes = (
        ("actor_mean.", "actor_log_std") if global_dimension else ()
    )
    return (*compression_prefixes, "critic.", *global_prefixes)


@dataclass
class Order9OnlineTrainingResult(SchemaBase):
    training_version: str
    stage_id: str
    policy_family: Order9PolicyFamily
    update_index: int
    rollout_manifest_path: str
    rollout_manifest_sha256: str
    parent_checkpoint_path: str
    parent_checkpoint_sha256: str
    checkpoint_path: str
    checkpoint_sha256: str
    metrics_path: str
    metrics_sha256: str
    consumed_environment_steps: int
    ppo_update: Order9PPOUpdateResult
    random_seed: int
    consumed_rollout_manifest_sha256s: list[str]
    metadata: dict[str, Any] = field(default_factory=dict)

    def validate(self) -> None:
        if self.training_version != ORDER9_ONLINE_TRAINING_VERSION:
            raise SchemaValidationError("Order9 online training version mismatch")
        for name in (
            "stage_id",
            "rollout_manifest_path",
            "parent_checkpoint_path",
            "checkpoint_path",
            "metrics_path",
        ):
            require_non_empty(str(getattr(self, name)), f"Order9OnlineTrainingResult.{name}")
        if self.update_index < 0 or self.random_seed < 0:
            raise SchemaValidationError("Order9 PPO update index/seed must be non-negative")
        if self.consumed_environment_steps < 1:
            raise SchemaValidationError("Order9 PPO must consume positive environment steps")
        for name in (
            "rollout_manifest_sha256",
            "parent_checkpoint_sha256",
            "checkpoint_sha256",
            "metrics_sha256",
        ):
            _require_sha256(str(getattr(self, name)), name)
        if (
            not self.consumed_rollout_manifest_sha256s
            or len(self.consumed_rollout_manifest_sha256s)
            != len(set(self.consumed_rollout_manifest_sha256s))
            or self.consumed_rollout_manifest_sha256s[-1]
            != self.rollout_manifest_sha256
        ):
            raise SchemaValidationError(
                "Order9 PPO rollout lineage must be unique and end at this generation"
            )


@dataclass
class Order9JointOnlineTrainingResult(SchemaBase):
    training_version: str
    stage_id: str
    update_index: int
    rollout_manifest_path: str
    rollout_manifest_sha256: str
    parent_checkpoint_sha256_by_family: dict[str, str]
    checkpoint_path_by_family: dict[str, str]
    checkpoint_sha256_by_family: dict[str, str]
    metrics_path: str
    metrics_sha256: str
    consumed_environment_steps: int
    ppo_update_by_family: dict[str, Order9PPOUpdateResult]
    random_seed: int
    consumed_rollout_manifest_sha256s: list[str]
    metadata: dict[str, Any] = field(default_factory=dict)

    def validate(self) -> None:
        if self.training_version != ORDER9_ONLINE_TRAINING_VERSION:
            raise SchemaValidationError("Order9 joint training version mismatch")
        if self.update_index < 0 or self.random_seed < 0:
            raise SchemaValidationError("Order9 joint update index/seed must be non-negative")
        if self.consumed_environment_steps < 1:
            raise SchemaValidationError("Order9 joint PPO environment steps must be positive")
        expected = set(Order9PolicyFamily.values())
        mappings = (
            self.parent_checkpoint_sha256_by_family,
            self.checkpoint_path_by_family,
            self.checkpoint_sha256_by_family,
            self.ppo_update_by_family,
        )
        if any(set(mapping) != expected for mapping in mappings):
            raise SchemaValidationError("Order9 joint PPO requires all three policy families")
        for mapping in (
            self.parent_checkpoint_sha256_by_family,
            self.checkpoint_sha256_by_family,
        ):
            for digest in mapping.values():
                _require_sha256(digest, "joint checkpoint digest")
        for name in (
            "stage_id",
            "rollout_manifest_path",
            "metrics_path",
        ):
            require_non_empty(
                str(getattr(self, name)), f"Order9JointOnlineTrainingResult.{name}"
            )
        _require_sha256(self.rollout_manifest_sha256, "rollout_manifest_sha256")
        _require_sha256(self.metrics_sha256, "metrics_sha256")
        if (
            not self.consumed_rollout_manifest_sha256s
            or len(self.consumed_rollout_manifest_sha256s)
            != len(set(self.consumed_rollout_manifest_sha256s))
            or self.consumed_rollout_manifest_sha256s[-1]
            != self.rollout_manifest_sha256
        ):
            raise SchemaValidationError("Order9 joint rollout lineage is invalid")


def train_order9_ppo_update(
    config: Order9LearningConfig,
    *,
    stage_id: str,
    rollout_manifest_path: str | Path,
    rollout_bundle: Order9DatasetBundle | None = None,
    parent_checkpoint_path: str | Path,
    physical_model: PhysicalModel,
    output_dir: str | Path,
    git_revision: str,
    update_index: int,
    device: str | torch.device | None = None,
    additional_input_artifact_paths: Mapping[str, str | Path] | None = None,
    progress_callback: (
        Callable[[int, Mapping[str, float], Mapping[str, Any]], None] | None
    ) = None,
) -> Order9OnlineTrainingResult:
    """Consume one fresh on-policy generation and create one child checkpoint."""

    config.validate()
    stage = order9_stage_by_id(config, stage_id)
    require_order9_stage_execution_allowed(config, stage)
    if stage.learning_mode != Order9LearningMode.PPO:
        raise SchemaValidationError("Order9 online trainer accepts PPO stages only")
    if stage.learning_target == Order9LearningTarget.JOINT_OBJECT_TASK:
        raise SchemaValidationError(
            "joint training has three behavior checkpoints; use "
            "train_order9_joint_ppo_update"
        )
    if update_index < 0:
        raise SchemaValidationError("Order9 PPO update_index must be non-negative")
    require_non_empty(git_revision, "git_revision")
    family = _stage_family(stage)
    resolved_device = _resolve_device(device or config.production_runtime.device)
    parent = load_order9_stage_parent_checkpoint(
        config,
        stage,
        parent_checkpoint_path,
        device=resolved_device,
        expected_family=family,
        update_index=update_index,
    )
    _validate_parent(parent.metadata, stage, update_index, physical_model)
    bundle = _bound_rollout_bundle(rollout_manifest_path, rollout_bundle)
    validation = validate_order9_dataset_for_stage(
        bundle,
        stage,
        behavior_checkpoint_sha256=parent.sha256,
    )
    if not validation.valid:
        raise SchemaValidationError(
            "Order9 PPO dataset failed exact behavior replay contract: "
            + ",".join(validation.failures)
        )
    rollout_sha = bundle.manifest_sha256
    prior_rollouts = _prior_rollout_lineage(parent.metadata.metadata)
    if rollout_sha in prior_rollouts:
        raise SchemaValidationError(
            "Order9 PPO rollout generation was already consumed in this lineage"
        )
    environment_steps = _environment_step_count(bundle)
    optimization = order9_ppo_optimization(config, stage)
    seed = config.production_runtime.seed + stage.stage_index * 100_000 + update_index
    _seed_everything(seed)
    model = parent.model.to(resolved_device)
    model.train()
    optimizer = torch.optim.Adam(model.parameters(), lr=optimization.learning_rate)
    load_monitor = Order9RuntimeLoadMonitor(
        sample_interval_s=config.production_runtime.runtime_load_sample_interval_s,
        device=str(resolved_device),
    )
    load_monitor.start(torch_module=torch)
    update_started = time.perf_counter()
    live_callback = None
    if progress_callback is not None:
        live_callback = lambda step, metrics: progress_callback(
            step, metrics, load_monitor.latest_sample()
        )
    try:
        update = _apply_single_family_update(
            model,
            family=family,
            bundle=bundle,
            physical_model=physical_model,
            optimizer=optimizer,
            optimization=optimization,
            behavior_checkpoint_sha256=parent.sha256,
            seed=seed,
            progress_callback=live_callback,
        )
        if resolved_device.type == "cuda":
            torch.cuda.synchronize(resolved_device)
    finally:
        update_wall_elapsed_s = time.perf_counter() - update_started
        runtime_load = load_monitor.stop(torch_module=torch)
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    checkpoint_path = output / f"checkpoint_update_{update_index:06d}.pt"
    metrics_path = output / f"ppo_update_{update_index:06d}.json"
    result_path = output / f"training_result_update_{update_index:06d}.json"
    for path in (checkpoint_path, metrics_path, result_path):
        if path.exists():
            raise FileExistsError(f"Order9 PPO output already exists: {path}")
    input_hashes = order9_checkpoint_input_hashes(
        bundle,
        parent_checkpoint_path=parent_checkpoint_path,
        source_order3_checkpoint_path=None,
        additional_paths=additional_input_artifact_paths or {},
    )
    metrics = _checkpoint_metrics(update, environment_steps, update_index)
    rollout_lineage = [*prior_rollouts, rollout_sha]
    metadata = build_order9_checkpoint_metadata(
        model,
        stage=stage,
        schedule_hash=order9_schedule_hash(config),
        physical_model_hash=physical_model.stable_hash(),
        git_revision=git_revision,
        random_seed=seed,
        input_artifact_hashes=input_hashes,
        parent_checkpoint_sha256=parent.sha256,
        source_order3_checkpoint_sha256=parent.metadata.source_order3_checkpoint_sha256,
        metrics=metrics,
        trainer_version=ORDER9_ONLINE_TRAINING_VERSION,
        extra_metadata={
            "ppo_update_index": update_index,
            "rollout_dataset_manifest_sha256": rollout_sha,
            "consumed_rollout_manifest_sha256s": rollout_lineage,
            "one_fresh_generation_one_update": True,
            "on_policy_behavior_checkpoint_sha256": parent.sha256,
        },
    )
    checkpoint_sha = save_order9_policy_checkpoint(
        checkpoint_path, model=model, metadata=metadata
    )
    metrics_payload = {
        "training_version": ORDER9_ONLINE_TRAINING_VERSION,
        "stage_id": stage.stage_id,
        "stage_index": stage.stage_index,
        "policy_family": family.value,
        "update_index": update_index,
        "random_seed": seed,
        "rollout_manifest_path": bundle.manifest_path,
        "rollout_manifest_sha256": rollout_sha,
        "parent_checkpoint_path": str(parent_checkpoint_path),
        "parent_checkpoint_sha256": parent.sha256,
        "checkpoint_path": str(checkpoint_path),
        "checkpoint_sha256": checkpoint_sha,
        "consumed_environment_steps": environment_steps,
        "update_wall_elapsed_s": update_wall_elapsed_s,
        "consumed_environment_steps_per_s": (
            environment_steps / update_wall_elapsed_s
        ),
        "runtime_load": runtime_load,
        "optimization": optimization.to_dict(),
        "ppo_update": update.to_dict(),
        "one_fresh_generation_one_update": True,
        "promotion_evaluation_completed": False,
    }
    _atomic_write_text(metrics_path, _json_text(metrics_payload))
    result = Order9OnlineTrainingResult(
        training_version=ORDER9_ONLINE_TRAINING_VERSION,
        stage_id=stage.stage_id,
        policy_family=family,
        update_index=update_index,
        rollout_manifest_path=bundle.manifest_path,
        rollout_manifest_sha256=rollout_sha,
        parent_checkpoint_path=str(parent_checkpoint_path),
        parent_checkpoint_sha256=parent.sha256,
        checkpoint_path=str(checkpoint_path),
        checkpoint_sha256=checkpoint_sha,
        metrics_path=str(metrics_path),
        metrics_sha256=hash_file(metrics_path),
        consumed_environment_steps=environment_steps,
        ppo_update=update,
        random_seed=seed,
        consumed_rollout_manifest_sha256s=rollout_lineage,
        metadata={
            "result_path": str(result_path),
            "device": str(resolved_device),
            "promotion_evaluation_completed": False,
        },
    )
    result.validate()
    _atomic_write_text(result_path, result.to_json(indent=2) + "\n")
    return result


def train_order9_tensor_pi_l_ppo_update(
    config: Order9LearningConfig,
    *,
    stage_id: str,
    rollout_manifest_path: str | Path,
    rollout_bundle: Order9TensorPiLDatasetBundle,
    parent_checkpoint_path: str | Path,
    physical_model: PhysicalModel,
    output_dir: str | Path,
    git_revision: str,
    update_index: int,
    device: str | torch.device | None = None,
    additional_input_artifact_paths: Mapping[str, str | Path] | None = None,
    progress_callback: (
        Callable[[int, Mapping[str, float], Mapping[str, Any]], None] | None
    ) = None,
    c3_action_contract: str | None = None,
) -> Order9OnlineTrainingResult:
    """Consume one immutable tensor generation without record/JSONL conversion."""

    config.validate()
    stage = order9_stage_by_id(config, stage_id)
    require_order9_stage_execution_allowed(config, stage)
    if (
        stage.learning_mode != Order9LearningMode.PPO
        or stage.learning_target != Order9LearningTarget.PI_L
    ):
        raise SchemaValidationError(
            "Order9 tensor-native trainer accepts pi_L PPO stages only"
        )
    if update_index < 0:
        raise SchemaValidationError("Order9 PPO update_index must be non-negative")
    if c3_action_contract is not None and stage.stage_id != (
        "c3_pi_l_ppo_arbitrary_morphology"
    ):
        raise SchemaValidationError("explicit C3 action contract requires C3")
    require_non_empty(git_revision, "git_revision")
    manifest_path = Path(rollout_manifest_path).resolve()
    if manifest_path.is_dir():
        manifest_path = manifest_path / "manifest.json"
    if (
        Path(rollout_bundle.manifest_path).resolve() != manifest_path
        or hash_file(manifest_path) != rollout_bundle.manifest_sha256
    ):
        raise SchemaValidationError(
            "Order9 tensor rollout bundle does not match its manifest"
        )
    resolved_device = _resolve_device(device or config.production_runtime.device)
    parent = load_order9_stage_parent_checkpoint(
        config,
        stage,
        parent_checkpoint_path,
        device=resolved_device,
        expected_family=Order9PolicyFamily.PI_L,
        update_index=update_index,
    )
    _validate_parent(parent.metadata, stage, update_index, physical_model)
    validation = validate_order9_tensor_pi_l_dataset_for_stage(
        rollout_bundle,
        config=config,
        stage_id=stage_id,
        behavior_checkpoint_sha256=parent.sha256,
    )
    if not validation.valid:
        raise SchemaValidationError(
            "Order9 tensor PPO dataset failed behavior contract: "
            + ",".join(validation.failures)
        )
    if c3_action_contract is not None and any(
        artifact.metadata.get("c3_action_contract") != c3_action_contract
        for artifact in (
            *rollout_bundle.train_artifacts,
            *rollout_bundle.validation_artifacts,
        )
    ):
        raise SchemaValidationError(
            "Order9 tensor PPO rollout action contract differs"
        )
    rollout_sha = rollout_bundle.manifest_sha256
    prior_rollouts = _prior_rollout_lineage(parent.metadata.metadata)
    if rollout_sha in prior_rollouts:
        raise SchemaValidationError(
            "Order9 PPO rollout generation was already consumed in this lineage"
        )
    environment_steps = rollout_bundle.manifest.environment_step_count
    optimization = order9_ppo_optimization(config, stage)
    boundary_fine_tune = None
    if (
        stage.stage_id == "c3_pi_l_ppo_arbitrary_morphology"
        and config.optimization.c3_boundary_fine_tune.enabled
    ):
        boundary_fine_tune = config.optimization.c3_boundary_fine_tune
        optimization = replace(
            optimization,
            epochs_per_update=boundary_fine_tune.epochs_per_update,
            learning_rate=(
                optimization.learning_rate
                * boundary_fine_tune.learning_rate_scale
            ),
        )
    seed = config.production_runtime.seed + stage.stage_index * 100_000 + update_index
    _seed_everything(seed)
    model = parent.model.to(resolved_device)
    if not isinstance(model, Order9PhaseConditionedActorCritic):
        raise TypeError("Order9 tensor-native checkpoint model type mismatch")
    model.train()
    compression_only_actor_objective = bool(
        boundary_fine_tune is not None
        and boundary_fine_tune.compression_only_actor_objective
    )
    joint_head_only_actor_update = bool(
        boundary_fine_tune is not None
        and boundary_fine_tune.joint_head_only_actor_update
    )
    contact_residual_only_actor_update = bool(
        boundary_fine_tune is not None
        and boundary_fine_tune.contact_residual_only_actor_update
    )
    if c3_action_contract is not None:
        if c3_action_contract not in ORDER9_C3_ACTION_CONTRACTS:
            raise SchemaValidationError("Order9 C3 PPO action contract is invalid")
        if not isinstance(
            model,
            (
                Order9ContactResidualPhaseConditionedActorCritic,
                Order9ContactSpacePhaseConditionedActorCritic,
            ),
        ):
            raise SchemaValidationError(
                "Order9 C3 action-contract update requires a v5/v6/v7 actor"
            )
        if order9_c3_action_contract_uses_full_policy(c3_action_contract):
            # The full contract trains one shared actor without module-count
            # switches: graph/recurrent trunk, all global and joint heads, the
            # independent compression head, and the critic are all live.
            compression_only_actor_objective = False
            joint_head_only_actor_update = False
            contact_residual_only_actor_update = False
            for parameter in model.parameters():
                parameter.requires_grad = True
        else:
            global_dimension = order9_c3_action_contract_global_dimension(
                c3_action_contract
            )
            contact_residual_only_actor_update = global_dimension == 0
            trainable_prefixes = _order9_c3_action_contract_trainable_prefixes(
                model,
                global_dimension=global_dimension,
            )
            for parameter_name, parameter in model.named_parameters():
                parameter.requires_grad = parameter_name.startswith(
                    trainable_prefixes
                )
    elif contact_residual_only_actor_update:
        if not isinstance(
            model, Order9ContactResidualPhaseConditionedActorCritic
        ):
            raise SchemaValidationError(
                "Order9 contact-residual-only update requires a v5/v6 actor"
            )
        for parameter_name, parameter in model.named_parameters():
            trainable_prefixes = (
                (
                    "contact_compression_actor_mean.",
                    "contact_compression_actor_log_std",
                    "contact_compression_module_count_bias",
                    "critic.",
                )
                if isinstance(
                    model, Order9MorphologyInvariantCompressionActorCritic
                )
                else ("contact_residual_decoder.", "critic.")
            )
            parameter.requires_grad = parameter_name.startswith(trainable_prefixes)
    elif joint_head_only_actor_update:
        for parameter_name, parameter in model.named_parameters():
            parameter.requires_grad = parameter_name.startswith(
                ("joint_decoder.", "critic.")
            )
    trainable_parameters = [
        parameter for parameter in model.parameters() if parameter.requires_grad
    ]
    if not trainable_parameters:
        raise SchemaValidationError("Order9 tensor PPO has no trainable parameters")
    optimizer = torch.optim.Adam(
        trainable_parameters, lr=optimization.learning_rate
    )
    load_monitor = Order9RuntimeLoadMonitor(
        sample_interval_s=config.production_runtime.runtime_load_sample_interval_s,
        device=str(resolved_device),
    )
    load_monitor.start(torch_module=torch)
    update_started = time.perf_counter()
    live_callback = None
    if progress_callback is not None:
        live_callback = lambda step, metrics: progress_callback(
            step, metrics, load_monitor.latest_sample()
        )
    try:
        # PyTorch 2.10's CUDA autograd worker repeatedly faulted inside the
        # host libcuda driver during long topology-stratified updates on this
        # workstation.  Backward remains mathematically identical when the
        # autograd engine executes its ready queue on one thread; only
        # independent backward nodes are no longer scheduled concurrently.
        # Scope the setting to this update and record it in PPO provenance.
        with torch.autograd.set_multithreading_enabled(False):
            update = update_order9_tensor_pi_l_ppo(
                model,
                rollout_bundle.train_artifacts,
                physical_model=physical_model,
                optimizer=optimizer,
                config=optimization,
                behavior_checkpoint_sha256=parent.sha256,
                seed=seed,
                boundary_fine_tune=boundary_fine_tune,
                compression_only_actor_objective=(
                    compression_only_actor_objective
                ),
                joint_head_only_actor_update=(
                    joint_head_only_actor_update
                ),
                contact_residual_only_actor_update=(
                    contact_residual_only_actor_update
                ),
                c3_action_contract=c3_action_contract,
                progress_callback=live_callback,
            )
        if resolved_device.type == "cuda":
            torch.cuda.synchronize(resolved_device)
    finally:
        update_wall_elapsed_s = time.perf_counter() - update_started
        runtime_load = load_monitor.stop(torch_module=torch)

    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    checkpoint_path = output / f"checkpoint_update_{update_index:06d}.pt"
    metrics_path = output / f"ppo_update_{update_index:06d}.json"
    result_path = output / f"training_result_update_{update_index:06d}.json"
    for path in (checkpoint_path, metrics_path, result_path):
        if path.exists():
            raise FileExistsError(f"Order9 PPO output already exists: {path}")
    input_hashes = order9_checkpoint_input_hashes(
        rollout_bundle,
        parent_checkpoint_path=parent_checkpoint_path,
        source_order3_checkpoint_path=None,
        additional_paths=additional_input_artifact_paths or {},
    )
    metrics = _checkpoint_metrics(update, environment_steps, update_index)
    rollout_lineage = [*prior_rollouts, rollout_sha]
    metadata = build_order9_checkpoint_metadata(
        model,
        stage=stage,
        schedule_hash=order9_schedule_hash(config),
        physical_model_hash=physical_model.stable_hash(),
        git_revision=git_revision,
        random_seed=seed,
        input_artifact_hashes=input_hashes,
        parent_checkpoint_sha256=parent.sha256,
        source_order3_checkpoint_sha256=(
            parent.metadata.source_order3_checkpoint_sha256
        ),
        metrics=metrics,
        trainer_version=ORDER9_ONLINE_TRAINING_VERSION,
        extra_metadata={
            "ppo_update_index": update_index,
            "rollout_dataset_manifest_sha256": rollout_sha,
            "consumed_rollout_manifest_sha256s": rollout_lineage,
            "one_fresh_generation_one_update": True,
            "on_policy_behavior_checkpoint_sha256": parent.sha256,
            "tensor_native_ppo": True,
            "topology_stratified_update": (
                rollout_bundle.manifest.metadata.get("topology_stratified_train")
                is True
            ),
            "record_schema_materialization": False,
            "jsonl_materialization": False,
            "c3_action_contract": c3_action_contract,
            "factorized_actor_credit_enabled": bool(
                boundary_fine_tune is not None
                and boundary_fine_tune.factorized_actor_credit_enabled
            ),
            "factorized_actor_credit_version": (
                ORDER9_FACTORIZED_ACTOR_CREDIT_VERSION
                if boundary_fine_tune is not None
                and boundary_fine_tune.factorized_actor_credit_enabled
                else None
            ),
            "factorized_actor_credit_channels": (
                list(ORDER9_FACTORIZED_ACTOR_CREDIT_CHANNELS)
                if boundary_fine_tune is not None
                and boundary_fine_tune.factorized_actor_credit_enabled
                else None
            ),
            "contact_head_extra_optimizer_contract": (
                ORDER9_CONTACT_HEAD_EXTRA_OPTIMIZER_CONTRACT
                if boundary_fine_tune is not None
                and boundary_fine_tune.contact_head_extra_optimizer_passes > 0
                else None
            ),
            "contact_head_extra_optimizer_passes": (
                int(boundary_fine_tune.contact_head_extra_optimizer_passes)
                if boundary_fine_tune is not None
                else 0
            ),
        },
    )
    checkpoint_sha = save_order9_policy_checkpoint(
        checkpoint_path, model=model, metadata=metadata
    )
    metrics_payload = {
        "training_version": ORDER9_ONLINE_TRAINING_VERSION,
        "stage_id": stage.stage_id,
        "stage_index": stage.stage_index,
        "policy_family": Order9PolicyFamily.PI_L.value,
        "update_index": update_index,
        "random_seed": seed,
        "rollout_manifest_path": rollout_bundle.manifest_path,
        "rollout_manifest_sha256": rollout_sha,
        "parent_checkpoint_path": str(parent_checkpoint_path),
        "parent_checkpoint_sha256": parent.sha256,
        "checkpoint_path": str(checkpoint_path),
        "checkpoint_sha256": checkpoint_sha,
        "consumed_environment_steps": environment_steps,
        "update_wall_elapsed_s": update_wall_elapsed_s,
        "consumed_environment_steps_per_s": environment_steps
        / update_wall_elapsed_s,
        "runtime_load": runtime_load,
        "optimization": optimization.to_dict(),
        "ppo_update": update.to_dict(),
        "one_fresh_generation_one_update": True,
        "tensor_native_ppo": True,
        "promotion_evaluation_completed": False,
        "c3_action_contract": c3_action_contract,
        "factorized_actor_credit_enabled": bool(
            boundary_fine_tune is not None
            and boundary_fine_tune.factorized_actor_credit_enabled
        ),
        "factorized_actor_credit_version": (
            ORDER9_FACTORIZED_ACTOR_CREDIT_VERSION
            if boundary_fine_tune is not None
            and boundary_fine_tune.factorized_actor_credit_enabled
            else None
        ),
        "factorized_actor_credit_channels": (
            list(ORDER9_FACTORIZED_ACTOR_CREDIT_CHANNELS)
            if boundary_fine_tune is not None
            and boundary_fine_tune.factorized_actor_credit_enabled
            else None
        ),
    }
    _atomic_write_text(metrics_path, _json_text(metrics_payload))
    result = Order9OnlineTrainingResult(
        training_version=ORDER9_ONLINE_TRAINING_VERSION,
        stage_id=stage.stage_id,
        policy_family=Order9PolicyFamily.PI_L,
        update_index=update_index,
        rollout_manifest_path=rollout_bundle.manifest_path,
        rollout_manifest_sha256=rollout_sha,
        parent_checkpoint_path=str(parent_checkpoint_path),
        parent_checkpoint_sha256=parent.sha256,
        checkpoint_path=str(checkpoint_path),
        checkpoint_sha256=checkpoint_sha,
        metrics_path=str(metrics_path),
        metrics_sha256=hash_file(metrics_path),
        consumed_environment_steps=environment_steps,
        ppo_update=update,
        random_seed=seed,
        consumed_rollout_manifest_sha256s=rollout_lineage,
        metadata={
            "result_path": str(result_path),
            "device": str(resolved_device),
            "tensor_native_ppo": True,
            "promotion_evaluation_completed": False,
        },
    )
    result.validate()
    _atomic_write_text(result_path, result.to_json(indent=2) + "\n")
    return result


def train_order9_joint_ppo_update(
    config: Order9LearningConfig,
    *,
    stage_id: str,
    rollout_manifest_path: str | Path,
    parent_checkpoint_paths_by_family: Mapping[
        Order9PolicyFamily | str, str | Path
    ],
    physical_model: PhysicalModel,
    output_dir: str | Path,
    git_revision: str,
    update_index: int,
    device: str | torch.device | None = None,
    additional_input_artifact_paths: Mapping[str, str | Path] | None = None,
) -> Order9JointOnlineTrainingResult:
    """Apply one configured factorized PPO update to pi_L, pi_H, and pi_D."""

    config.validate()
    stage = order9_stage_by_id(config, stage_id)
    require_order9_stage_execution_allowed(config, stage)
    if (
        stage.learning_mode != Order9LearningMode.PPO
        or stage.learning_target != Order9LearningTarget.JOINT_OBJECT_TASK
    ):
        raise SchemaValidationError(
            "Order9 joint trainer is restricted to the joint-object-task stage"
        )
    if update_index < 0:
        raise SchemaValidationError("Order9 joint update_index must be non-negative")
    require_non_empty(git_revision, "git_revision")
    paths = {
        Order9PolicyFamily(family): Path(path)
        for family, path in parent_checkpoint_paths_by_family.items()
    }
    expected_families = set(Order9PolicyFamily)
    if set(paths) != expected_families:
        raise SchemaValidationError(
            "Order9 joint training requires pi_L, pi_H, and pi_D parents"
        )
    resolved_device = _resolve_device(device or config.production_runtime.device)
    schedule_hash = order9_schedule_hash(config)
    parents = {
        family: load_order9_policy_checkpoint(
            path,
            device=resolved_device,
            expected_family=family,
            expected_schedule_hash=schedule_hash,
        )
        for family, path in paths.items()
    }
    for parent in parents.values():
        _validate_parent(parent.metadata, stage, update_index, physical_model)
    behavior_hashes = {
        family.value: parent.sha256 for family, parent in parents.items()
    }
    bundle = load_order9_dataset(rollout_manifest_path)
    validation = validate_order9_dataset_for_stage(
        bundle,
        stage,
        behavior_checkpoint_sha256=behavior_hashes,
    )
    if not validation.valid:
        raise SchemaValidationError(
            "Order9 joint PPO dataset failed behavior replay: "
            + ",".join(validation.failures)
        )
    rollout_sha = bundle.manifest_sha256
    prior_rollouts = _combined_prior_rollout_lineage(parents)
    if rollout_sha in prior_rollouts:
        raise SchemaValidationError(
            "Order9 joint PPO rollout generation was already consumed"
        )
    environment_steps = _environment_step_count(bundle)
    optimization = config.optimization.joint_ppo
    seed = config.production_runtime.seed + stage.stage_index * 100_000 + update_index
    updates: dict[Order9PolicyFamily, Order9PPOUpdateResult] = {}
    load_monitor = Order9RuntimeLoadMonitor(
        sample_interval_s=config.production_runtime.runtime_load_sample_interval_s,
        device=str(resolved_device),
    )
    load_monitor.start(torch_module=torch)
    update_started = time.perf_counter()
    try:
        for offset, family in enumerate(Order9PolicyFamily):
            family_seed = seed + 10_000 * offset
            _seed_everything(family_seed)
            model = parents[family].model.to(resolved_device)
            model.train()
            optimizer = torch.optim.Adam(
                model.parameters(), lr=optimization.learning_rate
            )
            updates[family] = _apply_single_family_update(
                model,
                family=family,
                bundle=bundle,
                physical_model=physical_model,
                optimizer=optimizer,
                optimization=optimization,
                behavior_checkpoint_sha256=parents[family].sha256,
                seed=family_seed,
            )
        if resolved_device.type == "cuda":
            torch.cuda.synchronize(resolved_device)
    finally:
        update_wall_elapsed_s = time.perf_counter() - update_started
        runtime_load = load_monitor.stop(torch_module=torch)
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    checkpoint_paths = {
        family: output / f"checkpoint_{family.value}_update_{update_index:06d}.pt"
        for family in Order9PolicyFamily
    }
    metrics_path = output / f"joint_ppo_update_{update_index:06d}.json"
    result_path = output / f"joint_training_result_update_{update_index:06d}.json"
    for path in (*checkpoint_paths.values(), metrics_path, result_path):
        if path.exists():
            raise FileExistsError(f"Order9 joint PPO output already exists: {path}")
    rollout_lineage = [*prior_rollouts, rollout_sha]
    checkpoint_hashes: dict[Order9PolicyFamily, str] = {}
    for family in Order9PolicyFamily:
        parent = parents[family]
        other_parent_paths = {
            f"joint_parent_{other.value}": path
            for other, path in paths.items()
            if other != family
        }
        input_hashes = order9_checkpoint_input_hashes(
            bundle,
            parent_checkpoint_path=paths[family],
            source_order3_checkpoint_path=None,
            additional_paths={
                **other_parent_paths,
                **dict(additional_input_artifact_paths or {}),
            },
        )
        metrics = _checkpoint_metrics(
            updates[family], environment_steps, update_index
        )
        checkpoint_metadata = build_order9_checkpoint_metadata(
            parent.model,
            stage=stage,
            schedule_hash=schedule_hash,
            physical_model_hash=physical_model.stable_hash(),
            git_revision=git_revision,
            random_seed=seed + 10_000 * list(Order9PolicyFamily).index(family),
            input_artifact_hashes=input_hashes,
            parent_checkpoint_sha256=parent.sha256,
            source_order3_checkpoint_sha256=(
                parent.metadata.source_order3_checkpoint_sha256
            ),
            metrics=metrics,
            trainer_version=ORDER9_ONLINE_TRAINING_VERSION,
            extra_metadata={
                "ppo_update_index": update_index,
                "joint_factorized_ppo": True,
                "joint_policy_families": list(Order9PolicyFamily.values()),
                "joint_parent_checkpoint_sha256_by_family": behavior_hashes,
                "rollout_dataset_manifest_sha256": rollout_sha,
                "consumed_rollout_manifest_sha256s": rollout_lineage,
                "one_fresh_generation_one_update": True,
                "on_policy_behavior_checkpoint_sha256": parent.sha256,
            },
        )
        checkpoint_hashes[family] = save_order9_policy_checkpoint(
            checkpoint_paths[family],
            model=parent.model,
            metadata=checkpoint_metadata,
        )
    metrics_payload = {
        "training_version": ORDER9_ONLINE_TRAINING_VERSION,
        "stage_id": stage.stage_id,
        "stage_index": stage.stage_index,
        "update_index": update_index,
        "random_seed": seed,
        "rollout_manifest_path": bundle.manifest_path,
        "rollout_manifest_sha256": rollout_sha,
        "parent_checkpoint_sha256_by_family": behavior_hashes,
        "checkpoint_path_by_family": {
            family.value: str(path) for family, path in checkpoint_paths.items()
        },
        "checkpoint_sha256_by_family": {
            family.value: digest for family, digest in checkpoint_hashes.items()
        },
        "consumed_environment_steps": environment_steps,
        "update_wall_elapsed_s": update_wall_elapsed_s,
        "consumed_environment_steps_per_s": (
            environment_steps / update_wall_elapsed_s
        ),
        "runtime_load": runtime_load,
        "optimization": optimization.to_dict(),
        "ppo_update_by_family": {
            family.value: update.to_dict() for family, update in updates.items()
        },
        "joint_factorized_ppo": True,
        "one_fresh_generation_one_update": True,
        "promotion_evaluation_completed": False,
    }
    _atomic_write_text(metrics_path, _json_text(metrics_payload))
    result = Order9JointOnlineTrainingResult(
        training_version=ORDER9_ONLINE_TRAINING_VERSION,
        stage_id=stage.stage_id,
        update_index=update_index,
        rollout_manifest_path=bundle.manifest_path,
        rollout_manifest_sha256=rollout_sha,
        parent_checkpoint_sha256_by_family=behavior_hashes,
        checkpoint_path_by_family={
            family.value: str(path) for family, path in checkpoint_paths.items()
        },
        checkpoint_sha256_by_family={
            family.value: digest for family, digest in checkpoint_hashes.items()
        },
        metrics_path=str(metrics_path),
        metrics_sha256=hash_file(metrics_path),
        consumed_environment_steps=environment_steps,
        ppo_update_by_family={
            family.value: update for family, update in updates.items()
        },
        random_seed=seed,
        consumed_rollout_manifest_sha256s=rollout_lineage,
        metadata={
            "result_path": str(result_path),
            "device": str(resolved_device),
            "joint_factorized_ppo": True,
            "promotion_evaluation_completed": False,
        },
    )
    result.validate()
    _atomic_write_text(result_path, result.to_json(indent=2) + "\n")
    return result


def _apply_single_family_update(
    model: nn.Module,
    *,
    family: Order9PolicyFamily,
    bundle: Order9DatasetBundle,
    physical_model: PhysicalModel,
    optimizer: torch.optim.Optimizer,
    optimization: Order9PPOOptimizationConfig,
    behavior_checkpoint_sha256: str,
    seed: int,
    progress_callback: Callable[[int, Mapping[str, float]], None] | None = None,
) -> Order9PPOUpdateResult:
    if family == Order9PolicyFamily.PI_L:
        if not isinstance(model, Order9PhaseConditionedActorCritic):
            raise TypeError("Order9 pi_L checkpoint model type mismatch")
        records: Sequence[LowLevelControlRecord] = _training_records(
            bundle.low_level_records
        )
        return update_order9_pi_l_ppo(
            model,
            records,
            physical_model=physical_model,
            optimizer=optimizer,
            config=optimization,
            behavior_checkpoint_sha256=behavior_checkpoint_sha256,
            seed=seed,
            progress_callback=progress_callback,
        )
    if family == Order9PolicyFamily.PI_H:
        if not isinstance(model, Order9AutoregressiveHighLevelPolicy):
            raise TypeError("Order9 pi_H checkpoint model type mismatch")
        trajectory_records: Sequence[InteractionTrajectoryRecord] = _training_records(
            bundle.trajectory_records
        )
        return update_order9_pi_h_ppo(
            model,
            trajectory_records,
            optimizer=optimizer,
            config=optimization,
            behavior_checkpoint_sha256=behavior_checkpoint_sha256,
            seed=seed,
        )
    if not isinstance(model, Order9AutoregressiveDesignPolicy):
        raise TypeError("Order9 pi_D checkpoint model type mismatch")
    design_records: Sequence[SequentialDesignTrajectoryRecord] = _training_records(
        bundle.sequential_design_records
    )
    return update_order9_pi_d_ppo(
        model,
        design_records,
        physical_model=physical_model,
        optimizer=optimizer,
        config=optimization,
        behavior_checkpoint_sha256=behavior_checkpoint_sha256,
        seed=seed,
    )


def _stage_family(stage: Order9CurriculumStage) -> Order9PolicyFamily:
    if stage.learning_target == Order9LearningTarget.PI_L:
        return Order9PolicyFamily.PI_L
    if stage.learning_target == Order9LearningTarget.PI_H_TRAJECTORY:
        return Order9PolicyFamily.PI_H
    if stage.learning_target == Order9LearningTarget.PI_D:
        return Order9PolicyFamily.PI_D
    raise SchemaValidationError(
        f"Order9 PPO target {stage.learning_target.value!r} requires a different runner"
    )


def _validate_parent(
    metadata,
    stage: Order9CurriculumStage,
    update_index: int,
    physical_model: PhysicalModel,
) -> None:
    if metadata.physical_model_hash != physical_model.stable_hash():
        raise SchemaValidationError("Order9 PPO parent physical-model hash mismatch")
    if metadata.curriculum_stage_index > stage.stage_index:
        raise SchemaValidationError("Order9 PPO parent comes from a later stage")
    if metadata.curriculum_stage_index < stage.stage_index:
        if update_index != 0:
            raise SchemaValidationError(
                "first checkpoint from an earlier stage must start at PPO update zero"
            )
        return
    if metadata.curriculum_stage_id != stage.stage_id:
        raise SchemaValidationError("Order9 same-index PPO parent stage identity mismatch")
    if (
        metadata.metadata.get("warm_start_only") is True
        and metadata.metadata.get("warm_start_requires_fresh_on_policy_ppo") is True
    ):
        if update_index != 0:
            raise SchemaValidationError(
                "Order9 warm-start initializer must begin at PPO update zero"
            )
        return
    previous = metadata.metadata.get("ppo_update_index")
    if not isinstance(previous, int) or previous + 1 != update_index:
        raise SchemaValidationError("Order9 PPO parent update lineage is not contiguous")


def _environment_step_count(bundle: Order9DatasetBundle) -> int:
    value = bundle.manifest.metadata.get("on_policy_environment_step_count")
    if not isinstance(value, int) or isinstance(value, bool) or value < 1:
        raise SchemaValidationError(
            "Order9 PPO manifest must declare positive on_policy_environment_step_count"
        )
    if bundle.manifest.metadata.get("one_fresh_generation") is not True:
        raise SchemaValidationError(
            "Order9 PPO manifest must identify one fresh rollout generation"
        )
    return value


def _bound_rollout_bundle(
    rollout_manifest_path: str | Path,
    supplied: Order9DatasetBundle | None,
) -> Order9DatasetBundle:
    if supplied is None:
        return load_order9_dataset(rollout_manifest_path)
    expected = Path(rollout_manifest_path)
    if expected.is_dir():
        expected = expected / "manifest.json"
    if (
        Path(supplied.manifest_path).resolve() != expected.resolve()
        or hash_file(expected) != supplied.manifest_sha256
    ):
        raise SchemaValidationError(
            "Order9 preloaded rollout bundle does not match its manifest"
        )
    return supplied


def _prior_rollout_lineage(metadata: Mapping[str, Any]) -> list[str]:
    value = metadata.get("consumed_rollout_manifest_sha256s", [])
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        raise SchemaValidationError("Order9 parent rollout lineage metadata is invalid")
    for digest in value:
        _require_sha256(digest, "consumed_rollout_manifest_sha256s[]")
    if len(value) != len(set(value)):
        raise SchemaValidationError("Order9 parent rollout lineage contains duplicates")
    return list(value)


def _combined_prior_rollout_lineage(parents: Mapping[Order9PolicyFamily, Any]) -> list[str]:
    lineages = {
        family: _prior_rollout_lineage(parent.metadata.metadata)
        for family, parent in parents.items()
    }
    current_stage_parents = [
        values
        for family, values in lineages.items()
        if parents[family].metadata.metadata.get("joint_factorized_ppo") is True
    ]
    if current_stage_parents and any(
        values != current_stage_parents[0] for values in current_stage_parents[1:]
    ):
        raise SchemaValidationError("Order9 joint parent rollout lineages diverged")
    combined: list[str] = []
    for family in Order9PolicyFamily:
        for digest in lineages[family]:
            if digest not in combined:
                combined.append(digest)
    return combined


def _checkpoint_metrics(
    update: Order9PPOUpdateResult,
    environment_steps: int,
    update_index: int,
) -> dict[str, float]:
    return {
        "ppo_update_index": float(update_index),
        "sample_count": float(update.sample_count),
        "environment_steps": float(environment_steps),
        "actor_loss": float(update.actor_loss),
        "value_loss": float(update.value_loss),
        "entropy": float(update.entropy),
        "total_loss": float(update.total_loss),
        "approximate_kl": float(update.approximate_kl),
        "clipped_fraction": float(update.clipped_fraction),
    }


def _training_records(values: Sequence[Any]) -> list[Any]:
    selected = [record for record in values if record.split == DatasetSplit.TRAIN]
    if not selected:
        raise SchemaValidationError("Order9 PPO rollout has no train records")
    return selected


def _resolve_device(value: str | torch.device) -> torch.device:
    device = torch.device(value)
    if device.type == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("Order9 production config requests unavailable CUDA")
    return device


def _seed_everything(seed: int) -> None:
    random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def _json_text(value: Mapping[str, Any]) -> str:
    return json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def _atomic_write_text(path: Path, value: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent, prefix=f".{path.name}.", suffix=".tmp"
    )
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(value)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_name, path)
    except BaseException:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise


def _require_sha256(value: str, path: str) -> None:
    if len(value) != 64 or any(character not in "0123456789abcdef" for character in value):
        raise SchemaValidationError(f"{path} must be a lowercase SHA-256 digest")


__all__ = [
    "ORDER9_ONLINE_TRAINING_VERSION",
    "Order9JointOnlineTrainingResult",
    "Order9OnlineTrainingResult",
    "train_order9_joint_ppo_update",
    "train_order9_ppo_update",
    "train_order9_tensor_pi_l_ppo_update",
]
